<?php

/*

 This took bloody forever to put into arrays. All the SQL commands for UseBB .2 packaged for easy installation.

 */

$TABLES = array(

    1 => "CREATE TABLE usebb_bans (id int(11) NOT NULL auto_increment,name varchar(255) NOT NULL default '',email varchar(255) NOT NULL default '',ip_addr varchar(23) NOT NULL default '',PRIMARY KEY  (id))",
    2 => "CREATE TABLE usebb_cats ( id int(11) NOT NULL auto_increment,name varchar(255) NOT NULL default '',sort_id int(11) NOT NULL default '0',PRIMARY KEY  (id))",
    3 => "CREATE TABLE usebb_config (name varchar(255) NOT NULL default '',content text NOT NULL,PRIMARY KEY  (name))",
    4 => "CREATE TABLE usebb_forums (id int(11) NOT NULL auto_increment,name varchar(255) NOT NULL default '', cat_id int(11) NOT NULL default '0',descr text NOT NULL,status int(1) NOT NULL default '1',topics int(11) NOT NULL default '0',posts int(11) NOT NULL default '0',last_topic_id int(11) NOT NULL default '0',sort_id int(11) NOT NULL default '0',auth varchar(10) NOT NULL default '0011222223',auto_lock int(11) NOT NULL default '0',PRIMARY KEY  (id))",
    5 => "CREATE TABLE usebb_language (name varchar(255) NOT NULL default '',language varchar(255) NOT NULL default '',content text NOT NULL)",
    6 => "CREATE TABLE usebb_moderators (forum_id int(11) NOT NULL default '0',user_id int(11) NOT NULL default '0')",
    7 => "CREATE TABLE usebb_posts (id int(11) NOT NULL auto_increment,topic_id int(11) NOT NULL default '0',poster_id int(11) NOT NULL default '0',poster_guest varchar(255) NOT NULL default '',poster_ip_addr varchar(23) NOT NULL default '',content text NOT NULL,post_time int(10) NOT NULL default '0',post_edit_time int(10) NOT NULL default '0',post_edit_by int(11) NOT NULL default '0',enable_bbcode int(1) NOT NULL default '1',enable_smilies int(1) NOT NULL default '1',enable_sig int(1) NOT NULL default '1',enable_html int(1) NOT NULL default '0',PRIMARY KEY  (id))",
    8 => "CREATE TABLE usebb_sessions (sess_id varchar(32) NOT NULL default '',user_id int(11) NOT NULL default '0',ip_addr varchar(23) NOT NULL default '',started int(10) NOT NULL default '0',updated int(10) NOT NULL default '0',location varchar(255) NOT NULL default '',pages int(11) NOT NULL default '0',PRIMARY KEY  (sess_id))",
    9 => "CREATE TABLE usebb_stats (name varchar(255) NOT NULL default '',content text NOT NULL,PRIMARY KEY  (name))",
    10 => "CREATE TABLE usebb_templates (name varchar(255) NOT NULL default '',template varchar(255) NOT NULL default '',content text NOT NULL)",
    11 => "CREATE TABLE usebb_templates_config (name varchar(255) NOT NULL default '',template varchar(255) NOT NULL default '',content text NOT NULL)",
    12 => "CREATE TABLE usebb_topics (id int(11) NOT NULL auto_increment,forum_id int(11) NOT NULL default '0',topic_title varchar(255) NOT NULL default '',first_post_id int(11) NOT NULL default '0',last_post_id int(11) NOT NULL default '0',count_replies int(11) NOT NULL default '0',count_views int(11) NOT NULL default '0', status_locked int(1) NOT NULL default '0',status_sticky int(1) NOT NULL default '0',PRIMARY KEY  (id))",
    13 => "CREATE TABLE usebb_users (id int(11) NOT NULL auto_increment,name varchar(255) NOT NULL default '',email varchar(255) NOT NULL default '',email_show int(1) NOT NULL default '0', passwd varchar(32) NOT NULL default '',regdate int(10) NOT NULL default '0',level int(1) NOT NULL default '0',rank varchar(255) NOT NULL default '',active int(1) NOT NULL default '0',active_key varchar(32) NOT NULL default '',banned int(1) NOT NULL default '0',banned_reason text NOT NULL,last_login int(10) NOT NULL default '0',last_login_show int(1) NOT NULL default '0',posts int(11) NOT NULL default '0',template varchar(255) NOT NULL default '',language varchar(255) NOT NULL default '',date_format varchar(255) NOT NULL default '',timezone float NOT NULL default '0',dst int(1) NOT NULL default '0',enable_quickreply int(1) NOT NULL default '0',return_to_topic_after_posting int(1) NOT NULL default '0',avatar_type int(1) NOT NULL default '0',avatar_remote varchar(255) NOT NULL default '',signature text NOT NULL,location varchar(255) NOT NULL default '',website varchar(255) NOT NULL default '',occupation varchar(255) NOT NULL default '',interests varchar(255) NOT NULL default '',msnm varchar(255) NOT NULL default '',yahoom varchar(255) NOT NULL default '',aim varchar(255) NOT NULL default '',icq varchar(255) NOT NULL default '',jabber varchar(255) NOT NULL default '',PRIMARY KEY  (id))"

    );

$DATA = array (
    
    1 => "INSERT INTO usebb_templates_config VALUES ('item_delimiter', 'default', '-')",
    2 => "INSERT INTO usebb_templates_config VALUES ('is_enabled', 'default', '1')",
    3 => "INSERT INTO usebb_templates_config VALUES ('template_name', 'default', 'UseBB Default Template')",
    4 => "INSERT INTO usebb_templates_config VALUES ('open_nonewposts_icon', 'default', 'open_nonewposts.gif')",
    5 => "INSERT INTO usebb_templates_config VALUES ('closed_nonewposts_icon', 'default', 'closed_nonewposts.gif')",
    6 => "INSERT INTO usebb_templates_config VALUES ('location_arrow', 'default', '&gt;')",
    7 => "INSERT INTO usebb_templates_config VALUES ('sig_format', 'default', '<hr /><div class=\"small\">%s</div>')",
    8 => "INSERT INTO usebb_templates_config VALUES ('textarea_rows', 'default', '10')",
    9 => "INSERT INTO usebb_templates_config VALUES ('textarea_cols', 'default', '60')",
    10 => "INSERT INTO usebb_templates_config VALUES ('quick_reply_textarea_rows', 'default', '5')",
    11 => "INSERT INTO usebb_templates VALUES ('normal_header', 'default', '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html>\r\n<head>\r\n  <title>{board_name}: {page_title}</title>\r\n  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"{css_url}\" />\r\n</head>\r\n<body>\r\n  <div align=\"center\">\r\n  <div class=\"main\">\r\n  \r\n  <table class=\"header\">\r\n  <tbody>\r\n    <tr>\r\n      <td class=\"logo\"><a href=\"{link_home}\"><img src=\"{img_dir}usebb.gif\" alt=\"UseBB\" title=\"Home\" /></a></td>\r\n      <td class=\"namebox\" nowrap=\"nowrap\"><div class=\"title\">{board_name}</div><div class=\"descr\">{board_descr}</div></td>\r\n    </tr>\r\n  </tbody>\r\n  </table>\r\n  \r\n  <div class=\"menu\">\r\n    <a href=\"{link_home}\" accesskey=\"h\">{home}</a><a href=\"{link_reg_panel}\">{reg_panel}</a><a href=\"{link_faq}\">{faq}</a><a href=\"{link_search}\">{search}</a><a href=\"{link_active}\">{active}</a><a href=\"{link_log_inout}\">{log_inout}</a>  </div>')",
    12 => "INSERT INTO usebb_templates VALUES ('normal_footer', 'default', '  <div class=\"linkbar\">\r\n    {link_bar}\r\n  </div>\r\n  <div class=\"banners\">\r\n    <a href=\"http://www.usebb.net\" target=\"_blank\"><img src=\"{img_dir}powered-by-usebb.gif\" alt=\"Powered by UseBB\" /></a>\r\n    <a href=\"http://validator.w3.org/check/referer\" target=\"_blank\"><img src=\"http://www.w3.org/Icons/valid-xhtml10\" alt=\"Valid XHTML 1.0!\" /></a>\r\n    <a href=\"http://jigsaw.w3.org/css-validator/\" target=\"_blank\"><img src=\"http://jigsaw.w3.org/css-validator/images/vcss\" alt=\"Valid CSS!\" /></a>\r\n    <a href=\"http://www.php.net\" target=\"_blank\"><img src=\"{img_dir}php-power-white.gif\" alt=\"Powered by PHP\" /></a>\r\n    <a href=\"http://www.mysql.com\" target=\"_blank\"><img src=\"{img_dir}powered-by-mysql-88x31.png\" alt=\"Powered by MySQL\" /></a>\r\n  </div>\r\n  <div class=\"copyright\">\r\n<!--\r\nWe request not to remove the following copyright notice including the link to the UseBB Home Page.\r\nThis shows your respect to everyone involved in UseBB\'s development and promotes the use of UseBB.\r\nIf you don\'t want to show the Copyright notice, just leave the Powered by UseBB line. If you\r\ncompletely alter or remove the notice, support at our community forums will be affected.\r\n-->\r\n    {copyright}\r\n  </div>\r\n  \r\n  </div>\r\n  </div>\r\n</body>\r\n\r\n</html>')",
    13 => "INSERT INTO usebb_templates VALUES ('forumlist_header', 'default', '  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\">{forum}</th>\r\n      <th>{topics}</th>\r\n      <th>{posts}</th>\r\n      <th nowrap=\"nowrap\">{latest_post}</th>\r\n    </tr>')",
    14 => "INSERT INTO usebb_templates VALUES ('css', 'default', 'body {\r\n  margin-top: 20px;\r\n  margin-left: 20px;\r\n  margin-right: 20px;\r\n  background-color: #FFFFFF;\r\n  }\r\nbody, td, th {\r\n  font-family: verdana, sans-serif;\r\n  font-size: 10pt;\r\n  color: #000000;\r\n  }\r\nimg {\r\n  border: 0px;\r\n  }\r\nform {\r\n  margin: 0px;\r\n  }\r\nhr {\r\n  border: 0px solid silver;\r\n  border-top-width: 1px;\r\n  height: 0px;\r\n  }\r\n.small {\r\n  font-size: 8pt;\r\n  }\r\na:link, a:active, a:visited {\r\n  color: #336699;\r\n  text-decoration: none;\r\n  }\r\na:hover {\r\n  color: #7F0000;\r\n  text-decoration: underline;\r\n  }\r\na.administrator:link, a.administrator:active, a.administrator:visited {\r\n  color: red;\r\n  }\r\na.moderator:link, a.moderator:active, a.moderator:visited {\r\n  color: blue;\r\n  }\r\ninput, select, textarea {\r\n  border: 1px solid silver;\r\n  background-color: #FFFFFF;\r\n  font-size: 10pt;\r\n  }\r\ntextarea {\r\n  font-family: verdana, sans-serif;\r\n  }\r\n.main {\r\n  width: 90%;\r\n  }\r\n.header {\r\n  border-collapse: collapse;\r\n  width: 100%;\r\n  margin-bottom: 10px;\r\n  }\r\n.header td {\r\n  padding: 0px;\r\n  vertical-align: bottom;\r\n  }\r\n.header td.logo {\r\n  text-align: left;\r\n  width: 100%;\r\n  }\r\n.header td.namebox {\r\n  text-align: right;\r\n  }\r\n.header td.namebox .title {\r\n  font-family: \"trebuchet ms\"; sans-serif;\r\n  font-size: 16pt;\r\n  font-weight: bold;\r\n  letter-spacing: 1px;\r\n  color: #336699;\r\n  border-bottom: 2px solid #ebd6ad;\r\n  }\r\n.header td.namebox .descr {\r\n  font-style: italic;\r\n  padding-top: 2px;\r\n  }\r\n.menu {\r\n  border: 1px solid #336699;\r\n  background-image: url({img_dir}menubg.gif)\",\r\n  background-repeat: repeat-x;\r\n  background-color: #E5E5E5;\r\n  text-align: left;\r\n  padding-top: 4px;\r\n  padding-bottom: 4px;\r\n  margin-bottom: 20px;\r\n  font-size: 8pt;\r\n  }\r\n.menu a {\r\n  padding-left: 10px;\r\n  padding-right: 10px;\r\n  padding-top: 4px;\r\n  padding-bottom: 4px;\r\n  border-right: 1px solid #336699;\r\n  }\r\n.menu a:hover {\r\n  background-image: url({img_dir}menubg2.gif)\",\r\n  background-repeat: repeat-x;\r\n  background-color: #FFFFFF;\r\n  text-decoration: none;\r\n  border-right: 1px solid #336699;\r\n  }\r\n.locationbar {\r\n  text-align: left;\r\n  margin-bottom: 20px;\r\n  }\r\n.maintable {\r\n  border-collapse: collapse;\r\n  border-left: 1px solid #336699;\r\n  border-right: 1px solid #336699;\r\n  border-bottom: 2px solid #336699;\r\n  width: 100%;\r\n  margin-bottom: 20px;\r\n  }\r\n.maintable th {\r\n  color: #EBD6AD;\r\n  font-weight: bold;\r\n  background-color: #336699;\r\n  background-image: url({img_dir}tableheadbg.gif)\",\r\n  background-position: top;\r\n  background-repeat: repeat-x;\r\n  text-align: left;\r\n  padding: 6px;\r\n  padding-top: 3px;\r\n  padding-bottom: 3px;\r\n  border-left: 1px solid #336699;\r\n  border-top: 1px solid #336699;\r\n  }\r\n.maintable td {\r\n  background-color: #EFEFEF;\r\n  padding: 6px;\r\n  text-align: left;\r\n  border-left: 1px solid #336699;\r\n  border-top: 1px solid #336699;\r\n  vertical-align: middle;\r\n  }\r\n.maintable td.forumcat {\r\n  font-weight: bold;\r\n  letter-spacing: 1px;\r\n  background-image: url({img_dir}menubg.gif)\",\r\n  background-repeat: repeat-x;\r\n  background-color: #E5E5E5;\r\n  }\r\n.maintable td.toolbar {\r\n  background-image: url({img_dir}menubg.gif)\",\r\n  background-repeat: repeat-x;\r\n  background-color: #E5E5E5;\r\n  }\r\n.maintable td.td1 {\r\n  background-color: #EFEFEF;\r\n  }\r\n.maintable td.td2 {\r\n  background-color: #E5E5E5;\r\n  }\r\n.maintable tr.post td {\r\n  vertical-align: top;\r\n  }\r\n.maintable td.msgboxcontent, .maintable td.confirmformcontent {\r\n  padding: 18px;\r\n  text-align: center;\r\n  }\r\n.postlinks {\r\n  float: right;\r\n  font-size: 8pt;\r\n  }\r\n.panelmenu {\r\n  border-collapse: collapse;\r\n  border-left: 1px solid #336699;\r\n  border-right: 1px solid #336699;\r\n  border-bottom: 1px solid #336699;\r\n  margin-bottom: 20px;\r\n  }\r\n.panelmenu td {\r\n  background-color: #E5E5E5;\r\n  padding: 5px;\r\n  padding-left: 15px;\r\n  padding-right: 15px;\r\n  text-align: center;\r\n  border-left: 1px solid #336699;\r\n  border-top: 1px solid #336699;\r\n  vertical-align: middle;\r\n  font-size: 8pt;\r\n  }\r\n.banners {\r\n  text-align: center;\r\n  margin-bottom: 2px;\r\n  }\r\n.linkbar {\r\n  color: #323232;\r\n  margin-bottom: 20px;\r\n  font-size: 8pt;\r\n  }\r\n.copyright {\r\n  color: #323232;\r\n  margin-bottom: 20px;\r\n  font-size: 8pt;\r\n  }')",
    15 => "INSERT INTO usebb_templates VALUES ('panel_menu', 'default', '  <table class=\"panelmenu\">\r\n  <tbody>\r\n    <tr>\r\n      <td class=\"td2\"><b>{yourpanel}</b></td>\r\n      <td>{panel_home}</td>\r\n      <td>{view_profile}</td>\r\n      <td>{panel_profile}</td>\r\n      <td>{panel_options}</td>\r\n      <td>{panel_passwd}</td>\r\n    </tr>\r\n  </tbody>\r\n  </table>')",
    16 => "INSERT INTO usebb_templates VALUES ('forumlist_footer', 'default', '  </tbody>\r\n  </table>')",
    17 => "INSERT INTO usebb_templates VALUES ('topiclist_topic', 'default', '    <tr>\r\n      <td class=\"td1\" width=\"1\"><img src=\"{img_dir}{topic_icon}\" alt=\"{topic_status}\" /></td>\r\n      <td class=\"td1\" width=\"100%\">{topic_name}</td>\r\n      <td class=\"td1\" nowrap=\"nowrap\"><div class=\"small\">{author}</div></td>\r\n      <td class=\"td2\"><div align=\"center\">{replies}</div></td>\r\n      <td class=\"td2\"><div align=\"center\">{views}</div></td>\r\n      <td class=\"td1\" nowrap=\"nowrap\"><div class=\"small\">{author_date}</div></td>\r\n    </tr>')",
    18 => "INSERT INTO usebb_templates VALUES ('profile', 'default', '  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\">{title}</th>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{username}</td><td class=\"td1\">{username_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{userid}</td><td class=\"td1\">{userid_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{level}</td><td class=\"td1\">{level_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{rank}</td><td class=\"td1\">{rank_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{avatar}</td><td class=\"td1\">{avatar_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{regdate}</td><td class=\"td1\">{regdate_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{posts}</td><td class=\"td1\">{posts_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{postsperday}</td><td class=\"td1\">{postsperday_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{lastlogin}</td><td class=\"td1\">{lastlogin_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{location}</td><td class=\"td1\">{location_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{website}</td><td class=\"td1\">{website_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{occupation}</td><td class=\"td1\">{occupation_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{interests}</td><td class=\"td1\">{interests_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{signature}</td><td class=\"td1\">{signature_v}</td>\r\n    </tr>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\">{contact_info}</th>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{email}</td><td class=\"td1\">{email_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{msnm}</td><td class=\"td1\">{msnm_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{yahoom}</td><td class=\"td1\">{yahoom_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{aim}</td><td class=\"td1\">{aim_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{icq}</td><td class=\"td1\">{icq_v} {icq_status}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{jabber}</td><td class=\"td1\">{jabber_v}</td>\r\n    </tr>\r\n  </tbody>\r\n  </table>')",
    19 => "INSERT INTO usebb_templates VALUES ('register_form', 'default', '  {form_begin}\r\n  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\">{register_form}</th>\r\n    </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{user}</td>\r\n    <td class=\"td1\">{user_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{email}</td>\r\n    <td class=\"td1\">{email_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td colspan=\"2\" class=\"td1\"><div class=\"small\">{everything_required}</div></td>\r\n  </tr>\r\n  <tr>\r\n    <td colspan=\"2\" class=\"td2\"><div align=\"center\">{submit_button}&nbsp;{reset_button}</div></td>\r\n  </tr>\r\n  </tbody>\r\n  </table>\r\n  {form_end}')",
    20 => "INSERT INTO usebb_templates VALUES ('login_form', 'default', '  {form_begin}\r\n  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\">{login}</th>\r\n    </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{user}</td>\r\n    <td class=\"td1\">{user_input}<br /><div class=\"small\">{link_reg}</div></td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{password}</td>\r\n    <td class=\"td1\">{password_input}<br /><div class=\"small\">{link_sendpwd}</div></td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{remember}</td>\r\n    <td class=\"td1\">{remember_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td colspan=\"2\" class=\"td2\"><div align=\"center\">{submit_button}&nbsp;{reset_button}</div></td>\r\n  </tr>\r\n  </tbody>\r\n  </table>\r\n  {form_end}')",
    21 => "INSERT INTO usebb_templates VALUES ('msgbox', 'default', '  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th>{box_title}</th>\r\n    </tr>\r\n    <tr>\r\n      <td class=\"msgboxcontent\">{content}</td>\r\n    </tr>\r\n  </tbody>\r\n  </table>')",
    22 => "INSERT INTO usebb_templates VALUES ('sendpwd_form', 'default', '  {form_begin}\r\n  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\">{sendpwd}</th>\r\n    </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{user}</td>\r\n    <td class=\"td1\">{user_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{email}</td>\r\n    <td class=\"td1\">{email_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td colspan=\"2\" class=\"td1\"><div class=\"small\">{everything_required}</div></td>\r\n  </tr>\r\n  <tr>\r\n    <td colspan=\"2\" class=\"td2\"><div align=\"center\">{submit_button}&nbsp;{reset_button}</div></td>\r\n  </tr>\r\n  </tbody>\r\n  </table>\r\n  {form_end}')",
    23 => "INSERT INTO usebb_templates VALUES ('forumlist_cat', 'default', '  <tr>\r\n    <td colspan=\"5\" class=\"forumcat\">{cat_name}</td>\r\n  </tr>')",
    24 => "INSERT INTO usebb_templates VALUES ('forumlist_stats', 'default', '  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\">{stats_title}</th>\r\n    </tr>\r\n    <tr>\r\n      <td rowspan=\"2\" width=\"1\"><img src=\"{img_dir}stats.gif\" alt=\"{stats_title}\" /></td>\r\n      <td>{small_stats}<br />{newest_member}</td>\r\n    </tr>\r\n    <tr>\r\n      <td>{users_online}<br />\r\n      <div class=\"small\">{members_online}</div>\r\n      </td>\r\n    </tr>\r\n  </tbody>\r\n  </table>')",
    25 => "INSERT INTO usebb_templates VALUES ('edit_profile', 'default', '  {form_begin}\r\n  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\">{edit_profile}</th>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{email}</td><td class=\"td1\">{email_input}&nbsp;<span class=\"small\">{required}</span></td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{avatar}</td><td class=\"td1\">{avatar_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{location}</td><td class=\"td1\">{location_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{website}</td><td class=\"td1\">{website_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{occupation}</td><td class=\"td1\">{occupation_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{interests}</td><td class=\"td1\">{interests_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{signature}</td><td class=\"td1\">{signature_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{msnm}</td><td class=\"td1\">{msnm_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{yahoom}</td><td class=\"td1\">{yahoom_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{aim}</td><td class=\"td1\">{aim_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{icq}</td><td class=\"td1\">{icq_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{jabber}</td><td class=\"td1\">{jabber_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td colspan=\"2\" class=\"td2\"><div align=\"center\">{submit_button}&nbsp;{reset_button}</div></td>\r\n    </tr>\r\n  </tbody>\r\n  </table>\r\n  {form_end}')",
    26 => "INSERT INTO usebb_templates VALUES ('mail_form', 'default', '  {form_begin}\r\n  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\">{sendemail}</th>\r\n    </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{from}</td>\r\n    <td class=\"td1\">{from_v}</td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{to}</td>\r\n    <td class=\"td1\">{to_v}</td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{subject}</td>\r\n    <td class=\"td1\">{subject_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{body}</td><td class=\"td1\">{body_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td colspan=\"2\" class=\"td1\"><div class=\"small\">{everything_required}</div></td>\r\n  </tr>\r\n  <tr>\r\n    <td colspan=\"2\" class=\"td2\"><div align=\"center\">{submit_button}&nbsp;{reset_button}</div></td>\r\n  </tr>\r\n  </tbody>\r\n  </table>\r\n  {form_end}')",
    27 => "INSERT INTO usebb_templates VALUES ('panel_sess_info', 'default', '  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\">{title}</th>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{sess_id}</td><td class=\"td1\">{sess_id_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{ip_addr}</td><td class=\"td1\">{ip_addr_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{started}</td><td class=\"td1\">{started_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{updated}</td><td class=\"td1\">{updated_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{total_time}</td><td class=\"td1\">{total_time_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{pages}</td><td class=\"td1\">{pages_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{al}</td><td class=\"td1\">{al_v}</td>\r\n    </tr>\r\n  </tbody>\r\n  </table>')",
    28 => "INSERT INTO usebb_templates VALUES ('edit_options', 'default', '  {form_begin}\r\n  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\">{edit_options}</th>\r\n    </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{language}</td>\r\n    <td class=\"td1\">{language_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{template}</td>\r\n    <td class=\"td1\">{template_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{email_show}</td>\r\n    <td class=\"td1\">{email_show_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{last_login_show}</td>\r\n    <td class=\"td1\">{last_login_show_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{date_format}</td>\r\n    <td class=\"td1\">{date_format_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{timezone}</td>\r\n    <td class=\"td1\">{timezone_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{dst}</td>\r\n    <td class=\"td1\">{dst_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{quickreply}</td>\r\n    <td class=\"td1\">{quickreply_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{return_to_topic}</td>\r\n    <td class=\"td1\">{return_to_topic_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td colspan=\"2\" class=\"td2\"><div align=\"center\">{submit_button}&nbsp;{reset_button}</div></td>\r\n  </tr>\r\n  </tbody>\r\n  </table>\r\n  {form_end}')",
    29 => "INSERT INTO usebb_templates VALUES ('editpwd_form', 'default', '  {form_begin}\r\n  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\">{edit_pwd}</th>\r\n    </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{current_passwd}</td>\r\n    <td class=\"td1\">{current_passwd_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{new_passwd}</td>\r\n    <td class=\"td1\">{new_passwd1_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td width=\"25%\" class=\"td2\">{new_passwd_again}</td>\r\n    <td class=\"td1\">{new_passwd2_input}</td>\r\n  </tr>\r\n  <tr>\r\n    <td colspan=\"2\" class=\"td1\"><div class=\"small\">{everything_required}</div></td>\r\n  </tr>\r\n  <tr>\r\n    <td colspan=\"2\" class=\"td2\"><div align=\"center\">{submit_button}&nbsp;{reset_button}</div></td>\r\n  </tr>\r\n  </tbody>\r\n  </table>\r\n  {form_end}')",
    30 => "INSERT INTO usebb_templates VALUES ('location_bar', 'default', '  <div class=\"locationbar\">\r\n    &bull; {location_bar}\r\n  </div>')",
    31 => "INSERT INTO usebb_templates VALUES ('topiclist_header', 'default', '  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr>\r\n      <td colspan=\"6\" class=\"toolbar\"><div align=\"right\">\r\n        {forum_links}\r\n      </div></td>\r\n    </tr>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\" width=\"100%\">{topic}</th>\r\n      <th>{author}</th>\r\n      <th>{replies}</th>\r\n      <th>{views}</th>\r\n      <th nowrap=\"nowrap\">{latest_post}</th>\r\n    </tr>')",
    32 => "INSERT INTO usebb_templates VALUES ('forumlist_forum', 'default', '    <tr>\r\n      <td class=\"td1\"><img src=\"{img_dir}{forum_icon}\" alt=\"{forum_status}\" /></td>\r\n      <td class=\"td1\" width=\"100%\">{forum_name}<br /><div class=\"small\">{forum_descr}</div></td>\r\n      <td class=\"td2\"><div align=\"center\">{total_topics}</div></td>\r\n      <td class=\"td2\"><div align=\"center\">{total_posts}</div></td>\r\n      <td class=\"td1\" nowrap=\"nowrap\"><div class=\"small\">{latest_post}<br />{author_date}</div></td>\r\n    </tr>')",
    33 => "INSERT INTO usebb_templates VALUES ('topiclist_footer', 'default', '    <tr>\r\n      <td colspan=\"6\" class=\"toolbar\"><div align=\"right\">\r\n        {forum_links}\r\n      </div></td>\r\n    </tr>\r\n    <tr>\r\n      <td colspan=\"6\" class=\"td2\">\r\n        <div class=\"small\">{forum_moderators}</div>\r\n      </td>\r\n    </tr>\r\n  </tbody>\r\n  </table>')",
    33 => "INSERT INTO usebb_templates VALUES ('confirm_form', 'default', '  {form_begin}\r\n  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th>{title}</th>\r\n    </tr>\r\n  <tr>\r\n    <td class=\"confirmformcontent\">{content}</td>\r\n  </tr>\r\n  <tr>\r\n    <td class=\"td2\"><div align=\"center\">{submit_button}&nbsp;{cancel_button}</div></td>\r\n  </tr>\r\n  </tbody>\r\n  </table>\r\n  {form_end}')",
    34 => "INSERT INTO usebb_templates VALUES ('topic_header', 'default', '  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr>\r\n      <td colspan=\"2\" class=\"toolbar\"><div align=\"right\">\r\n        {topic_links}\r\n      </div></td>\r\n    </tr>\r\n    <tr class=\"tablehead\">\r\n      <th>{author}</th>\r\n      <th>{post}</th>\r\n    </tr>')",
    35 => "INSERT INTO usebb_templates VALUES ('topic_post', 'default', '    <tr class=\"post\">\r\n      <td class=\"td{colornum}\" width=\"15%\">\r\n        {poster_name}\r\n        <div class=\"small\">\r\n          {poster_rank}<br />\r\n          {poster_avatar}\r\n        </div>\r\n      </td>\r\n      <td class=\"td{colornum}\">\r\n        <div class=\"postlinks\">{post_links}</div>\r\n        <div class=\"small\">{post_anchor} - {post_date}</div>\r\n        <hr />{post_content}\r\n      </td>\r\n    </tr>')",
    36 => "INSERT INTO usebb_templates VALUES ('topic_footer', 'default', '    <tr>\r\n      <td colspan=\"2\" class=\"toolbar\"><div align=\"right\">\r\n        {topic_links}\r\n      </div></td>\r\n    </tr>\r\n    <tr>\r\n      <td colspan=\"2\" class=\"td2\">\r\n        <div class=\"small\">{action_links}</div>\r\n      </td>\r\n    </tr>\r\n  </tbody>\r\n  </table>')",
    37 => "INSERT INTO usebb_templates VALUES ('post_form', 'default', '  {form_begin}\r\n  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\">{post_title}</th>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{username}</td><td class=\"td1\">{username_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{subject}</td><td class=\"td1\">{subject_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{content}</td><td class=\"td1\">{content_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{options}</td><td class=\"td1\">{options_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td colspan=\"2\" class=\"td2\"><div align=\"center\">{submit_button}&nbsp;{reset_button}</div></td>\r\n    </tr>\r\n  </tbody>\r\n  </table>\r\n  {form_end}')",
    38 => "INSERT INTO usebb_templates VALUES ('quick_reply', 'default', '  {form_begin}\r\n  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\">{quick_reply}</th>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{username}</td><td class=\"td1\">{username_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{content}</td><td class=\"td1\">{content_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td colspan=\"2\" class=\"td2\"><div align=\"center\">{submit_button}&nbsp;{reset_button}</div></td>\r\n    </tr>\r\n  </tbody>\r\n  </table>\r\n  {form_end}')",
    39 => "INSERT INTO usebb_templates VALUES ('topiclist_notopics', 'default', '    <tr>\r\n      <td class=\"msgboxcontent\" colspan=\"6\">\r\n        {notopics}\r\n      </td>\r\n    </tr>')",
    40 => "INSERT INTO usebb_templates VALUES ('move_topic_form', 'default', '  {form_begin}\r\n  <table class=\"maintable\">\r\n  <tbody>\r\n    <tr class=\"tablehead\">\r\n      <th colspan=\"2\">{move_topic}</th>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{topic}</td><td class=\"td1\">{topic_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{old_forum}</td><td class=\"td1\">{old_forum_v}</td>\r\n    </tr>\r\n    <tr>\r\n      <td width=\"25%\" class=\"td2\">{new_forum}</td><td class=\"td1\">{new_forum_input}</td>\r\n    </tr>\r\n    <tr>\r\n      <td colspan=\"2\" class=\"td2\"><div align=\"center\">{submit_button}&nbsp;{cancel_button}</div></td>\r\n    </tr>\r\n  </tbody>\r\n  </table>\r\n  {form_end}')",
    41 => "INSERT INTO usebb_stats VALUES ('forums', '0')",
    42 => "INSERT INTO usebb_stats VALUES ('topics', '0')",
    43 => "INSERT INTO usebb_stats VALUES ('posts', '0')", 
    44 => "INSERT INTO usebb_stats VALUES ('members', '0')",
    45 => "INSERT INTO usebb_language VALUES ('Home', 'English', 'Home')",
    46 => "INSERT INTO usebb_language VALUES ('YourPanel', 'English', 'Your Panel')",
    47 => "INSERT INTO usebb_language VALUES ('Register', 'English', 'Register')",
    48 => "INSERT INTO usebb_language VALUES ('FAQ', 'English', 'FAQ')",
    49 => "INSERT INTO usebb_language VALUES ('Search', 'English', 'Search')",
    50 => "INSERT INTO usebb_language VALUES ('ActiveTopics', 'English', 'Active Topics')",
    51 => "INSERT INTO usebb_language VALUES ('LogIn', 'English', 'Log In')",
    52 => "INSERT INTO usebb_language VALUES ('LogOut', 'English', 'Log Out [ %s ]')",
    53 => "INSERT INTO usebb_language VALUES ('MemberList', 'English', 'Member List')",
    54 => "INSERT INTO usebb_language VALUES ('StaffList', 'English', 'Staff List')",
    55 => "INSERT INTO usebb_language VALUES ('Statistics', 'English', 'Statistics')",
    56 => "INSERT INTO usebb_language VALUES ('ContactAdmin', 'English', 'Contact Admin')",
    57 => "INSERT INTO usebb_language VALUES ('Forum', 'English', 'Forum')",
    58 => "INSERT INTO usebb_language VALUES ('Topics', 'English', 'Topics')",
    59 => "INSERT INTO usebb_language VALUES ('Posts', 'English', 'Posts')",
    60 => "INSERT INTO usebb_language VALUES ('LatestPost', 'English', 'Latest Post')",
    61 => "INSERT INTO usebb_language VALUES ('RSSFeed', 'English', 'RSS Feed')",
    62 => "INSERT INTO usebb_language VALUES ('NoNewPosts', 'English', 'No new posts')",
    63 => "INSERT INTO usebb_language VALUES ('Locked', 'English', 'Locked')",
    64 => "INSERT INTO usebb_language VALUES ('LastLogin', 'English', 'Last login')",
    65 => "INSERT INTO usebb_language VALUES ('VariousInfo', 'English', 'Various Information')",
    66 => "INSERT INTO usebb_language VALUES ('IndexStats', 'English', 'This board contains %d posts in %d topics posted by %d members.')",
    67 => "INSERT INTO usebb_language VALUES ('NewestMember', 'English', 'Welcome to our newest member: %s.')",
    68 => "INSERT INTO usebb_language VALUES ('OnlineUsers', 'English', 'There are %d members and %d guests online in the past %d minutes.')",
    69 => "INSERT INTO usebb_language VALUES ('Username', 'English', 'Username')",
    70 => "INSERT INTO usebb_language VALUES ('CurrentPassword', 'English', 'Current password')",
    71 => "INSERT INTO usebb_language VALUES ('UserID', 'English', 'User ID')",
    72 => "INSERT INTO usebb_language VALUES ('NoSuchForum', 'English', 'The forum %s does not exist (anymore) at this board!')",
    73 => "INSERT INTO usebb_language VALUES ('WrongPassword', 'English', 'Sorry, but that password isn\'t correct! Request a new password via the login form if you\'ve forgotten it.')",
    74 => "INSERT INTO usebb_language VALUES ('Reset', 'English', 'Reset')",
    75 => "INSERT INTO usebb_language VALUES ('SendPassword', 'English', 'Send a new password')",
    76 => "INSERT INTO usebb_language VALUES ('RegisterNewAccount', 'English', 'Register a new account')",
    77 => "INSERT INTO usebb_language VALUES ('RememberMe', 'English', 'Remember me')",
    78 => "INSERT INTO usebb_language VALUES ('Yes', 'English', 'Yes')",
    79 => "INSERT INTO usebb_language VALUES ('No', 'English', 'No')",
    80 => "INSERT INTO usebb_language VALUES ('NotActivated', 'English', 'Your account %s has not been activated yet. Please check your mail box you\'ve registered with on this forum for instructions on how to activate your account.')",
    81 => "INSERT INTO usebb_language VALUES ('Error', 'English', 'Error')",
    82 => "INSERT INTO usebb_language VALUES ('Profile', 'English', 'Profile of %s')",
    83 => "INSERT INTO usebb_language VALUES ('Level', 'English', 'Level')",
    84 => "INSERT INTO usebb_language VALUES ('Administrator', 'English', 'Administrator')",
    85 => "INSERT INTO usebb_language VALUES ('Moderator', 'English', 'Moderator')",
    86 => "INSERT INTO usebb_language VALUES ('Registered', 'English', 'Registered')",
    87 => "INSERT INTO usebb_language VALUES ('Email', 'English', 'E-mail address')",
    88 => "INSERT INTO usebb_language VALUES ('ContactInfo', 'English', 'Contact Information')",
    89 => "INSERT INTO usebb_language VALUES ('Password', 'English', 'Password')",
    90 => "INSERT INTO usebb_language VALUES ('EverythingRequired', 'English', 'All fields are required!')",
    91 => "INSERT INTO usebb_language VALUES ('UserAlreadyExists', 'English', 'Sorry, user %s already exists at this board. If it\'s yours, log in or request a new password. If not, please choose another username.')",
    92 => "INSERT INTO usebb_language VALUES ('RegisteredNotActivated', 'English', 'Your account %s has now been created. An e-mail has been dispatched to %s with instructions on how to activate your account. You need to activate in order to log in with your account.')",
    93 => "INSERT INTO usebb_language VALUES ('RegisteredActivated', 'English', 'Your account %s has now been created. An e-mail has been dispatched to %s with your login details.')",
    94 => "INSERT INTO usebb_language VALUES ('Never', 'English', 'Never')",
    95 => "INSERT INTO usebb_language VALUES ('Member', 'English', 'Member')",
    96 => "INSERT INTO usebb_language VALUES ('RegistrationActivationEmailBody', 'English', 'Hello,\r\n\r\nThis is the forum software of [board_name] speaking. You have just registered an account named [account_name], but it has not been activated yet. Please click the link below to activate your account:\r\n\r\n[activate_link]\r\n\r\nor copy-n-paste it to your browser. Then you can log in using this username and password:\r\n\r\nUsername: [account_name]\r\nPassword: [password]\r\n\r\nIf you forget your password, you can request a new one via the link on the login form. Thank you for registering!\r\n\r\n[board_name]\r\n[board_link]\r\n[admin_email]')",
    97 => "INSERT INTO usebb_language VALUES ('SendpwdActivationEmailSubject', 'English', 'New Password')",
    98 => "INSERT INTO usebb_language VALUES ('NoForums', 'English', 'This is an empty board. The administrator has not yet created any forums.')",
    99 => "INSERT INTO usebb_language VALUES ('AlreadyActivated', 'English', 'Account with ID %d has already been activated.')",
    100 => "INSERT INTO usebb_language VALUES ('Activate', 'English', 'Activate')",
    101 => "INSERT INTO usebb_language VALUES ('Activated', 'English', 'Your account %s has now been (re)activated. You are now able to log in with the password in the e-mail you received.')",
    102 => "INSERT INTO usebb_language VALUES ('WrongActivationKey', 'English', 'We were unable to activate your account with ID %d. The activation key is incorrect. Are you sure you didn\'t request a new password in the mean time?')",
    103 => "INSERT INTO usebb_language VALUES ('RegisterIt', 'English', 'You can create it via the \'Register\' link.')",
    104 => "INSERT INTO usebb_language VALUES ('BoardClosed', 'English', 'Board Closed')",
    105 => "INSERT INTO usebb_language VALUES ('SendpwdActivationEmailBody', 'English', 'Hello,\r\n\r\nThis is the forum software of [board_name] speaking. You have just requested a new password for account [account_name]. Please click the link below to reactivate your account:\r\n\r\n[activate_link]\r\n\r\nor copy-n-paste it to your browser. Then you can log in using this username and password:\r\n\r\nUsername: [account_name]\r\nPassword: [password]\r\n\r\nIf you forget your password, you can request a new one via the link on the login form. \r\n\r\n[board_name]\r\n[board_link]\r\n[admin_email]')",
    106 => "INSERT INTO usebb_language VALUES ('SendpwdEmailBody', 'English', 'Hello,\r\n\r\nThis is the forum software of [board_name] speaking. You have just requested a new password for account [account_name]. You can log in using this username and password:\r\n\r\nUsername: [account_name]\r\nPassword: [password]\r\n\r\nIf you forget your password, you can request a new one via the link on the login form. \r\n\r\n[board_name]\r\n[board_link]\r\n[admin_email]')",
    107 => "INSERT INTO usebb_language VALUES ('SendpwdEmailSubject', 'English', 'New Password')",
    108 => "INSERT INTO usebb_language VALUES ('SendpwdActivated', 'English', 'The new password for your account %s has been sent to %s. You are now able to login with your new password.')",
    109 => "INSERT INTO usebb_language VALUES ('SendpwdNotActivated', 'English', 'The new password for your account %s has been sent to %s, together with information on how to reactivate your account.')",
    110 => "INSERT INTO usebb_language VALUES ('ForumIndex', 'English', 'Forum Index')",
    112 => "INSERT INTO usebb_language VALUES ('MissingFields', 'English', 'The following fields were missing or incorrect: %s.')",
    113 => "INSERT INTO usebb_language VALUES ('TermsOfUseContent', 'English', '-Put your terms and conditions in here.-')",
    114 => "INSERT INTO usebb_language VALUES ('TermsOfUse', 'English', 'Terms Of Use')",
    115 => "INSERT INTO usebb_language VALUES ('RegistrationActivationEmailSubject', 'English', 'Account Activation')",
    116 => "INSERT INTO usebb_language VALUES ('NeedToBeLoggedIn', 'English', 'You need to be logged in in order to do this. Click the \'Log In\' link to log in or \'Register\' to create a new account.')",
    117 => "INSERT INTO usebb_language VALUES ('WrongEmail', 'English', 'Sorry, but %s isn\'t the correct e-mail address for your account %s. If you can\'t remember your e-mail address, please contact the board admin.')",
    118 => "INSERT INTO usebb_language VALUES ('Topic', 'English', 'Topic')",
    119 => "INSERT INTO usebb_language VALUES ('Author', 'English', 'Author')",
    120 => "INSERT INTO usebb_language VALUES ('Replies', 'English', 'Replies')",
    121 => "INSERT INTO usebb_language VALUES ('Views', 'English', 'Views')",
    122 => "INSERT INTO usebb_language VALUES ('Note', 'English', 'Note')",
    123 => "INSERT INTO usebb_language VALUES ('Hidden', 'English', 'Hidden')",
    124 => "INSERT INTO usebb_language VALUES ('ACP', 'English', 'Admin Control Panel')",
    125 => "INSERT INTO usebb_language VALUES ('SendMessage', 'English', 'Send a message')",
    126 => "INSERT INTO usebb_language VALUES ('NoViewableForums', 'English', 'You don\'t have permission to view any forums with this user level. If you are not logged in, do so. If you are logged in, you probably shouldn\'t be here.')",
    127 => "INSERT INTO usebb_language VALUES ('Rank', 'English', 'Rank')",
    128 => "INSERT INTO usebb_language VALUES ('Location', 'English', 'Location')",
    129 => "INSERT INTO usebb_language VALUES ('Website', 'English', 'Website')",
    130 => "INSERT INTO usebb_language VALUES ('Occupation', 'English', 'Occupation')",
    131 => "INSERT INTO usebb_language VALUES ('Interests', 'English', 'Interests')",
    132 => "INSERT INTO usebb_language VALUES ('MSNM', 'English', 'MSN Messenger')",
    133 => "INSERT INTO usebb_language VALUES ('YahooM', 'English', 'Yahoo Messenger')",
    134 => "INSERT INTO usebb_language VALUES ('AIM', 'English', 'AIM')",
    135 => "INSERT INTO usebb_language VALUES ('ICQ', 'English', 'ICQ')",
    136 => "INSERT INTO usebb_language VALUES ('Jabber', 'English', 'Jabber')",
    137 => "INSERT INTO usebb_language VALUES ('BannedIP', 'English', 'Your IP address %s has been banned from this board.')",
    138 => "INSERT INTO usebb_language VALUES ('Avatar', 'English', 'Avatar')",
    139 => "INSERT INTO usebb_language VALUES ('BannedUser', 'English', 'Banned Account')",
    140 => "INSERT INTO usebb_language VALUES ('BannedUserExplain', 'English', 'Your account %s has been banned from this board. The reason is:')",
    141 => "INSERT INTO usebb_language VALUES ('BannedUsername', 'English', 'The username %s has been banned on this board. Please choose another one.')",
    142 => "INSERT INTO usebb_language VALUES ('BannedEmail', 'English', 'The e-mail address %s has been banned on this board. Please choose another one.')",
    143 => "INSERT INTO usebb_language VALUES ('PostsPerDay', 'English', 'Posts per day')",
    144 => "INSERT INTO usebb_language VALUES ('BoardClosedOnlyAdmins', 'English', 'Only administrators can log in when the board is closed.')",
    145 => "INSERT INTO usebb_language VALUES ('NoPosts', 'English', 'No Posts')",
    146 => "INSERT INTO usebb_language VALUES ('AuthorDate', 'English', 'By %s on %s')",
    147 => "INSERT INTO usebb_language VALUES ('Re', 'English', 'Re:')",
    148 => "INSERT INTO usebb_language VALUES ('MailForm', 'English', 'Send an e-mail to %s')",
    149 => "INSERT INTO usebb_language VALUES ('SendEmail', 'English', 'Send a message to %s')",
    150 => "INSERT INTO usebb_language VALUES ('NoMails', 'English', 'This user has chosen not to receive any e-mails.')",
    151 => "INSERT INTO usebb_language VALUES ('UserEmailBody', 'English', 'Hello,\r\n\r\nThis is the forum software of [board_name] speaking. The user [username] has sent this message to you via our board. The message body follows.\r\n\r\n[board_name]\r\n[board_link]\r\n[admin_email]\r\n\r\n-----\r\n\r\n[body]')",
    152 => "INSERT INTO usebb_language VALUES ('EmailSent', 'English', 'Your e-mail to %s has been sent succesfully!')",
    153 => "INSERT INTO usebb_language VALUES ('To', 'English', 'To')",
    154 => "INSERT INTO usebb_language VALUES ('From', 'English', 'From')",
    155 => "INSERT INTO usebb_language VALUES ('Subject', 'English', 'Subject')",
    156 => "INSERT INTO usebb_language VALUES ('Body', 'English', 'Body')",
    157 => "INSERT INTO usebb_language VALUES ('Send', 'English', 'Send')",
    158 => "INSERT INTO usebb_language VALUES ('EditProfile', 'English', 'Edit Profile')",
    159 => "INSERT INTO usebb_language VALUES ('EditOptions', 'English', 'Edit Options')",
    160 => "INSERT INTO usebb_language VALUES ('EditPasswd', 'English', 'Edit Password')",
    161 => "INSERT INTO usebb_language VALUES ('PanelHome', 'English', 'Panel Home')",
    162 => "INSERT INTO usebb_language VALUES ('NewEmailNotActivated', 'English', 'Your profile has been edited succesfully. Because you have changed your e-mail address for your account %s, you need to reactivate it. An e-mail has been sent to %s with instructions on how to do this. You will be logged out in the mean time.')",
    163 => "INSERT INTO usebb_language VALUES ('Required', 'English', 'Required')",
    164 => "INSERT INTO usebb_language VALUES ('ViewProfile', 'English', 'View Profile')",
    165 => "INSERT INTO usebb_language VALUES ('NewEmailActivationEmailBody', 'English', 'Hello,\r\n\r\nThis is the forum software of [board_name] speaking. You have just altered the e-mail address of your account [account_name], but these has not been reactivated yet. Please click the link below to reactivate your account:\r\n\r\n[activate_link]\r\n\r\nor copy-n-paste it to your browser. Then you can log in using this username and password:\r\n\r\nUsername: [account_name]\r\nPassword: [password]\r\n\r\nIf you forget your password, you can request a new one via the link on the login form.\r\n\r\n[board_name]\r\n[board_link]\r\n[admin_email]')",
    166 => "INSERT INTO usebb_language VALUES ('NewEmailActivationEmailSubject', 'English', 'Account Reactivation')",
    167 => "INSERT INTO usebb_language VALUES ('Signature', 'English', 'Signature')",
    168 => "INSERT INTO usebb_language VALUES ('SessionInfo', 'English', 'Session Information')",
    169 => "INSERT INTO usebb_language VALUES ('SessionID', 'English', 'Session ID')",
    170 => "INSERT INTO usebb_language VALUES ('IPAddress', 'English', 'IP address')",
    171 => "INSERT INTO usebb_language VALUES ('Seconds', 'English', 'Seconds')",
    172 => "INSERT INTO usebb_language VALUES ('Updated', 'English', 'Updated')",
    173 => "INSERT INTO usebb_language VALUES ('Pages', 'English', 'Pages')",
    174 => "INSERT INTO usebb_language VALUES ('AutoLogin', 'English', 'Auto login')",
    175 => "INSERT INTO usebb_language VALUES ('Enabled', 'English', 'Enabled')",
    176 => "INSERT INTO usebb_language VALUES ('Disabled', 'English', 'Disabled')",
    177 => "INSERT INTO usebb_language VALUES ('Enable', 'English', 'Enable')",
    178 => "INSERT INTO usebb_language VALUES ('Disable', 'English', 'Disable')",
    179 => "INSERT INTO usebb_language VALUES ('AutoLoginSet', 'English', 'The auto login cookie has now been set.')",
    180 => "INSERT INTO usebb_language VALUES ('AutoLoginUnset', 'English', 'The auto login cookie has now been unset.')",
    181 => "INSERT INTO usebb_language VALUES ('RegistrationEmailBody', 'English', 'Hello,\r\n\r\nThis is the forum software of [board_name] speaking. You have just registered an account named [account_name]. You can log in using this username and password:\r\n\r\nUsername: [account_name]\r\nPassword: [password]\r\n\r\nIf you forget your password, you can request a new one via the link on the login form. Thank you for registering!\r\n\r\n[board_name]\r\n[board_link]\r\n[admin_email]')",
    182 => "INSERT INTO usebb_language VALUES ('RegistrationEmailSubject', 'English', 'Account Registration')",
    183 => "INSERT INTO usebb_language VALUES ('PublicEmail', 'English', 'Public e-mail address')",
    184 => "INSERT INTO usebb_language VALUES ('PublicLastLogin', 'English', 'Public last login time')",
    185 => "INSERT INTO usebb_language VALUES ('DateFormat', 'English', 'Date format')",
    186 => "INSERT INTO usebb_language VALUES ('Again', 'English', 'Again')",
    187 => "INSERT INTO usebb_language VALUES ('NewPassword', 'English', 'New password')",
    189 => "INSERT INTO usebb_language VALUES ('NewPasswordAgain', 'English', 'New password (again)')",
    190 => "INSERT INTO usebb_language VALUES ('PasswordEdited', 'English', 'Your password has been edited succesfully.')",
    191 => "INSERT INTO usebb_language VALUES ('DetailedOnlineList', 'English', 'Detailed online list')",
    192 => "INSERT INTO usebb_language VALUES ('OptionsEdited', 'English', 'Your board options have been edited succesfully.')",
    193 => "INSERT INTO usebb_language VALUES ('ProfileEdited', 'English', 'Your profile has been edited succesfully.')",
    194 => "INSERT INTO usebb_language VALUES ('Started', 'English', 'Started')",
    195 => "INSERT INTO usebb_language VALUES ('Minutes', 'English', 'Minutes')",
    196 => "INSERT INTO usebb_language VALUES ('Hours', 'English', 'Hours')",
    197 => "INSERT INTO usebb_language VALUES ('Days', 'English', 'Days')",
    198 => "INSERT INTO usebb_language VALUES ('Weeks', 'English', 'Weeks')",
    199 => "INSERT INTO usebb_language VALUES ('TotalTime', 'English', 'Total time')",
    200 => "INSERT INTO usebb_language VALUES ('NoTopics', 'English', 'This forum does not contain any topics. You could post the first one!')",
    201 => "INSERT INTO usebb_language VALUES ('NotPermitted', 'English', 'You don\'t have the appropriate permissions to do this. If in doubt, contact the administrator.')",
    202 => "INSERT INTO usebb_language VALUES ('Language', 'English', 'Language')",
    203 => "INSERT INTO usebb_language VALUES ('Template', 'English', 'Template')",
    204 => "INSERT INTO usebb_language VALUES ('NoSuchMember', 'English', 'The member %s does not exist (anymore) at this board.')",
    205 => "INSERT INTO usebb_language VALUES ('FeatureDisabledBecauseCookiesDisabled', 'English', 'This feature is disabled because this board can not set or read cookies with your browser.')",
    206 => "INSERT INTO usebb_language VALUES ('LogOutConfirm', 'English', 'Are you sure you wish to log out? Your auto login cookie will be erased!')",
    207 => "INSERT INTO usebb_language VALUES ('Cancel', 'English', 'Cancel')",
    208 => "INSERT INTO usebb_language VALUES ('Timezone', 'English', 'Timezone')",
    209 => "INSERT INTO usebb_language VALUES ('DST', 'English', 'Daylight saving times')",
    210 => "INSERT INTO usebb_language VALUES ('Sticky', 'English', 'Sticky')",
    211 => "INSERT INTO usebb_language VALUES ('PostNewTopic', 'English', 'Post new topic')",
    212 => "INSERT INTO usebb_language VALUES ('ForumIsLocked', 'English', 'Forum is locked')",
    213 => "INSERT INTO usebb_language VALUES ('NoSuchTopic', 'English', 'The topic %s does not exist (anymore) at this board.')",
    214 => "INSERT INTO usebb_language VALUES ('PostReply', 'English', 'Post reply')",
    215 => "INSERT INTO usebb_language VALUES ('TopicIsLocked', 'English', 'Topic is locked')",
    216 => "INSERT INTO usebb_language VALUES ('Post', 'English', 'Post')",
    217 => "INSERT INTO usebb_language VALUES ('Edit', 'English', 'Edit')",
    218 => "INSERT INTO usebb_language VALUES ('Delete', 'English', 'Delete')",
    219 => "INSERT INTO usebb_language VALUES ('Quote', 'English', 'Quote')",
    220 => "INSERT INTO usebb_language VALUES ('IPAddress', 'English', 'IP address')",
    221 => "INSERT INTO usebb_language VALUES ('ReplyTo', 'English', 'Reply to %s')",
    222 => "INSERT INTO usebb_language VALUES ('TopicIsLockedExplain', 'English', 'The topic you are trying to post in is locked. Only authorized people can still post replies.')",
    223 => "INSERT INTO usebb_language VALUES ('Content', 'English', 'Content')",
    224 => "INSERT INTO usebb_language VALUES ('Options', 'English', 'Options')",
    225 => "INSERT INTO usebb_language VALUES ('EnableBBCode', 'English', 'Enable BBCode.')",
    226 => "INSERT INTO usebb_language VALUES ('EnableSmilies', 'English', 'Enable smilies.')",
    227 => "INSERT INTO usebb_language VALUES ('EnableSig', 'English', 'Enable signature.')",
    228 => "INSERT INTO usebb_language VALUES ('EnableHTML', 'English', 'Enable HTML.')",
    229 => "INSERT INTO usebb_language VALUES ('LockTopicAfterPost', 'English', 'Lock topic after posting.')",
    230 => "NSERT INTO usebb_language VALUES ('Guest', 'English', 'Guest')",
    231 => "INSERT INTO usebb_language VALUES ('BackToPrevious', 'English', 'Back to the previous page')",
    232 => "INSERT INTO usebb_language VALUES ('NoSuchPost', 'English', 'The post %s does not exist (anymore) at this board.')",
    233 => "INSERT INTO usebb_language VALUES ('UserPostedImage', 'English', 'User posted image')",
    234 => "INSERT INTO usebb_language VALUES ('ForumIsLockedExplain', 'English', 'This forum is locked. Only authorized people can post new topics.')",
    235 => "INSERT INTO usebb_language VALUES ('MakeTopicSticky', 'English', 'Make the topic sticky.')",
    236 => "INSERT INTO usebb_language VALUES ('QuickReply', 'English', 'Quick reply')",
    237 => "INSERT INTO usebb_language VALUES ('ReturnToTopicAfterPosting', 'English', 'Return to the topic after posting.')",
    238 => "INSERT INTO usebb_language VALUES ('ModeratorsInThisForum', 'English', 'This forum is moderated by: %s.')",
    239 => "INSERT INTO usebb_language VALUES ('Nobody', 'English', 'Nobody')",
    240 => "INSERT INTO usebb_language VALUES ('DeleteTopic', 'English', 'Delete topic')",
    241 => "INSERT INTO usebb_language VALUES ('MoveTopic', 'English', 'Move topic')",
    242 => "INSERT INTO usebb_language VALUES ('LockTopic', 'English', 'Lock topic')",
    242 => "INSERT INTO usebb_language VALUES ('UnlockTopic', 'English', 'Unlock topic')",
    243 => "INSERT INTO usebb_language VALUES ('MakeSticky', 'English', 'Make sticky')",
    244 => "INSERT INTO usebb_language VALUES ('ConfirmDeleteTopic', 'English', 'Are you sure you want to delete the topic %s in the forum %s? This is irreversible!')",
    245 => "INSERT INTO usebb_language VALUES ('MakeNormalTopic', 'English', 'Make normal topic')",
    246 => "INSERT INTO usebb_language VALUES ('OldForum', 'English', 'Old forum')",
    247 => "INSERT INTO usebb_language VALUES ('NewForum', 'English', 'New forum')",
    248 => "INSERT INTO usebb_config VALUES ('session_name', 'usebb')",
    249 => "INSERT INTO usebb_config VALUES ('debug', '0')",
    250 => "INSERT INTO usebb_config VALUES ('allow_multi_sess', '1')",
    251 => "INSERT INTO usebb_config VALUES ('sess_max_lifetime', '60')",
    252 => "INSERT INTO usebb_config VALUES ('template', 'default')",
    253 => "INSERT INTO usebb_config VALUES ('output_compression', '0')",
    254 => "INSERT INTO usebb_config VALUES ('language', 'English')",
    255 => "INSERT INTO usebb_config VALUES ('board_name', 'My Board')",
    256 => "INSERT INTO usebb_config VALUES ('board_descr', 'My Board')",
    257 => "INSERT INTO usebb_config VALUES ('enable_memberlist', '0')",
    258 => "INSERT INTO usebb_config VALUES ('enable_stafflist', '0')",
    259 => "INSERT INTO usebb_config VALUES ('enable_stats', '0')",
    260 => "INSERT INTO usebb_config VALUES ('enable_contactadmin', '1')",
    261 => "INSERT INTO usebb_config VALUES ('admin_email', 'your_email@host.tld')",
    262 => "INSERT INTO usebb_config VALUES ('date_format', 'D M d, Y g:i a')",
    263 => "INSERT INTO usebb_config VALUES ('enable_rss', '0')",
    264 => "INSERT INTO usebb_config VALUES ('online_min_updated', '30')",
    265 => "INSERT INTO usebb_config VALUES ('cookie_domain', '')",
    266 => "INSERT INTO usebb_config VALUES ('cookie_secure', '0')",
    267 => "INSERT INTO usebb_config VALUES ('cookie_path', '')",
    268 => "INSERT INTO usebb_config VALUES ('users_must_activate', '1')",
    269 => "INSERT INTO usebb_config VALUES ('board_url', 'http://www.host.tld/usebb/')",
    270 => "INSERT INTO usebb_config VALUES ('board_closed', '0')",
    271 => "INSERT INTO usebb_config VALUES ('board_closed_reason', 'Just closed...')",
    272 => "INSERT INTO usebb_config VALUES ('username_max_length', '25')",
    273 => "INSERT INTO usebb_config VALUES ('guests_can_view_profiles', '1')",
    274 => "INSERT INTO usebb_config VALUES ('guests_can_access_board', '1')",
    275 => "INSERT INTO usebb_config VALUES ('email_view_level', '1')",
    276 => "INSERT INTO usebb_config VALUES ('view_hidden_email_addresses_min_level', '3')",
    277 => "INSERT INTO usebb_config VALUES ('guests_can_view_online_list', '1')",
    278 => "INSERT INTO usebb_config VALUES ('enable_online_list', '0')",
    279 => "INSERT INTO usebb_config VALUES ('sig_allow_bbcode', '1')",
    280 => "INSERT INTO usebb_config VALUES ('sig_allow_smilies', '1')",
    281 => "INSERT INTO usebb_config VALUES ('timezone', '0')",
    282 => "INSERT INTO usebb_config VALUES ('dst', '0')",
    283 => "INSERT INTO usebb_config VALUES ('enable_quickreply', '1')",
    285 => "INSERT INTO usebb_config VALUES ('return_to_topic_after_posting', '1')"
    
    );

?>